/* tslint:disable */
/* eslint-disable */
/**
 * AlterOrb API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A representation of a game achievement.
 * @export
 * @interface Achievement
 */
export interface Achievement {
    /**
     * The achievement\'s id.
     * @type {number}
     * @memberof Achievement
     */
    readonly achievementId?: number;
    /**
     * The achievement\'s name.
     * @type {string}
     * @memberof Achievement
     */
    readonly name?: string;
    /**
     * The achievement\'s unlock criteria.
     * @type {string}
     * @memberof Achievement
     */
    readonly criteria?: string;
    /**
     * How many orb coins does the achievement awards.
     * @type {number}
     * @memberof Achievement
     */
    readonly orbCoins?: number;
    /**
     * How many orb points does the achievement awards.
     * @type {number}
     * @memberof Achievement
     */
    readonly orbPoints?: number;
    /**
     * The id of the game that this achievement belongs to.
     * @type {number}
     * @memberof Achievement
     */
    readonly gameId?: number;
    /**
     * If this achievement is currently obtainable or not.
     * @type {boolean}
     * @memberof Achievement
     */
    readonly obtainable?: boolean;
}

export function AchievementFromJSON(json: any): Achievement {
    return AchievementFromJSONTyped(json, false);
}

export function AchievementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Achievement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'achievementId': !exists(json, 'achievementId') ? undefined : json['achievementId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'criteria': !exists(json, 'criteria') ? undefined : json['criteria'],
        'orbCoins': !exists(json, 'orbCoins') ? undefined : json['orbCoins'],
        'orbPoints': !exists(json, 'orbPoints') ? undefined : json['orbPoints'],
        'gameId': !exists(json, 'gameId') ? undefined : json['gameId'],
        'obtainable': !exists(json, 'obtainable') ? undefined : json['obtainable'],
    };
}

export function AchievementToJSON(value?: Achievement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


