/* tslint:disable */
/* eslint-disable */
/**
 * AlterOrb API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An AlterOrb game
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * The game id
     * @type {number}
     * @memberof Game
     */
    readonly id?: number;
    readonly name?: string;
    /**
     * How many achievements are obtainable in this game
     * @type {number}
     * @memberof Game
     */
    readonly obtainableAchievements?: number;
    /**
     * How many orb points can be obtained in this game
     * @type {number}
     * @memberof Game
     */
    readonly obtainableOrbPoints?: number;
}

export function GameFromJSON(json: any): Game {
    return GameFromJSONTyped(json, false);
}

export function GameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Game {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'obtainableAchievements': !exists(json, 'obtainableAchievements') ? undefined : json['obtainableAchievements'],
        'obtainableOrbPoints': !exists(json, 'obtainableOrbPoints') ? undefined : json['obtainableOrbPoints'],
    };
}

export function GameToJSON(value?: Game | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


