/* tslint:disable */
/* eslint-disable */
/**
 * AlterOrb API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An entry on the highscores using the orbpoints mode
 * @export
 * @interface HighscoresOrbPoints
 */
export interface HighscoresOrbPoints {
    /**
     * The player\'s display name
     * @type {string}
     * @memberof HighscoresOrbPoints
     */
    readonly displayName?: string;
    /**
     * How many orb points the player has
     * @type {number}
     * @memberof HighscoresOrbPoints
     */
    readonly orbPoints?: number;
}

export function HighscoresOrbPointsFromJSON(json: any): HighscoresOrbPoints {
    return HighscoresOrbPointsFromJSONTyped(json, false);
}

export function HighscoresOrbPointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HighscoresOrbPoints {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'orbPoints': !exists(json, 'orbPoints') ? undefined : json['orbPoints'],
    };
}

export function HighscoresOrbPointsToJSON(value?: HighscoresOrbPoints | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


