/* tslint:disable */
/* eslint-disable */
/**
 * AlterOrb API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerAchievement
 */
export interface PlayerAchievement {
    /**
     * The achievement id
     * @type {number}
     * @memberof PlayerAchievement
     */
    readonly id?: number;
    /**
     * The game id
     * @type {number}
     * @memberof PlayerAchievement
     */
    readonly gameId?: number;
    /**
     * An ISO-8601 timestamp of when the achievement was unlocked
     * @type {string}
     * @memberof PlayerAchievement
     */
    readonly unlockTimestamp?: string;
}

export function PlayerAchievementFromJSON(json: any): PlayerAchievement {
    return PlayerAchievementFromJSONTyped(json, false);
}

export function PlayerAchievementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerAchievement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'gameId': !exists(json, 'gameId') ? undefined : json['gameId'],
        'unlockTimestamp': !exists(json, 'unlockTimestamp') ? undefined : json['unlockTimestamp'],
    };
}

export function PlayerAchievementToJSON(value?: PlayerAchievement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


